### ISSUE TITLE
Difference vs GVls?

### ISSUE THREAD

**Issue by mna** [benwaffle/vala-language-server#108]
Hello,

I'm setting up a Vala dev environment and found out there were 2 active options for language servers, this one and GVls (https://blogs.gnome.org/despinosa/2020/03/02/gvls-0-14-0-released/).

Is one significantly more complete than the other? What are the main differences, is one more suited for a particular editor, do they have different goals? Maybe they were just started in parallel without knowing about the other, whatever the reasons it's fine, there's just little information for outsiders about why there are two and which should be used in which context or if they're just two valid and similar options.

Thanks!
Martin

**Comment by Prince781** [comment]
The quickest and shortest answer I can give is that VLS works, and GVls does not. If you don't believe me, try both of them out in any editor. :smirk: 

The longer answer:
VLS was the first project of its kind, created three years ago. Then came GVls and some other prototypical language servers. After awhile, only this project and GVls remain. VLS went through a long period of inactivity before we were able to pick up development again, and I think that's the reason why other projects popped up in the meantime.

GVls is currently the default Vala language server in GNOME Builder, but we are working on changing that. Right now, we have an out-of-tree plugin for GNOME Builder as a temporary fix (this gets installed with VLS). 

There are too many things VLS has over GVls to mention here. I'd encourage you to read the README or ask me a specific question, or again, just try them both out in any editor. The one thing GVls has over VLS is support for GNOME Builder's `workspace/configuration` message, but [we're working on that too](https://github.com/benwaffle/vala-language-server/tree/wip/gnome-builder). But this is almost moot because VLS was designed to work with any editor, unlike GVls, and so in many cases we're able to analyze the workspace configuration in the language server from various project backends.

**Comment by mna** [comment]
Okay, thanks :) I certainly do not want to start a flame war, but it's good to get a bit of context about this. I'll probably try Builder at some point but in general I prefer using vim, so I will try out this one for sure. In theory, if both implement the LSP, both should work with any editor, but then implementations matter of course.
