### ISSUE TITLE
Argument analysis for interpeter line in Vala scripts

### ISSUE THREAD

**Issue by gavr123456789** [benwaffle/vala-language-server#113]
I have a vala script file in my project that I use for compilation and build(because I don't know python) and I see errors in it because the server does not know that the script uses json(to search for target in meson-info)  
  
I am not at all sure about the solution to this issue. This could also be solved by adding argument analysis for first #! line(the first line in the script: `#!/usr/bin/env -S vala --pkg json-glib-1.0`)  
  
I think we need to somehow implement the ability to add files to ignore of the analysis. May be just ignore the ones that start with #! hmm

**Comment by Prince781** [comment]
VLS will only analyze files that are defined in `meson.build`. All other files will be analyzed separately as standalone files. So your script isn't being analyzed as part of your Meson project, but as something else separately. It makes sense that you're seeing errors because without a build file (currently either `meson.build` or `compile_commands.json`) there are no compile arguments.

So what you're asking is for VLS to analyze the interpreter line (`#! ...`) at the top of a file, only if the file is a standalone file.

**Comment by Prince781** [comment]
@gavr123456789 is this fixed now?

**Comment by gavr123456789** [comment]
Yes

**Comment by Prince781** [comment]
@gavr123456789 in the future, this issue shouldn't be closed until its corresponding fix has been merged (in this case, #110)

**Comment by lw64** [comment]
It seems like VLS doesnt recognize if the arguments after `#!/usr/bin/vala` get changed.
