### ISSUE TITLE
Will it be only for Visual Studio Code or editor agnostic?

### ISSUE THREAD

**Issue by AnderRasoVazquez** [benwaffle/vala-language-server#3]

**Comment by harisvsulaiman** [comment]
Hi,
Let me give my 2cents on this issue.

Language server protocol supports editors like atom and vscode. Other editors can implement it.

Since vscode has excellent support for LSP, I think this project will target vscode with a plugin too.

**Comment by thiagoabreu** [comment]
The vala-language-server is been tested against the [vala-code](https://github.com/thiagoabreu/vala-code) vscode plugin, because it has a good tooling for debugging the server.

But, as it's compliant to the [language server protocol](https://langserver.org/), any editor/plugin that implements a "vala language client" should work too.

**Comment by benwaffle** [comment]
it will work with any editor that supports the language server protocol
