### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by Prince781** [benwaffle/vala-language-server#54]
<s>There are severe memory leaks that must be taken care of.</s>

The severest leaks are gone now, but there's still more leaks to fix.

**Comment by Prince781** [comment]
@gavr123456789 these are leaks in the Vala *compiler* I'm talking about

**Comment by gavr123456789** [comment]
Wow, okey, this is not so important because the compiler works in fractions of seconds, and GCC takes up most of the time.

**Comment by Prince781** [comment]
@gavr123456789 no, it is important because VLS creates and destroys instances of the Vala compiler every time the project is modified

**Comment by gavr123456789** [comment]
![image](https://user-images.githubusercontent.com/30507409/75937824-1eead300-5e97-11ea-8e9b-23e945cc9258.png)
Ye, leak a real problem, looks like i just cant use it now.

**Comment by Prince781** [comment]
@gavr123456789 for now the solution is to just kill vls and let the plugin restart it

**Comment by gavr123456789** [comment]
@Prince781  These 10 GB leaked in about 3-5 minutes. Why didn't Philip's VLS leak? (by the way, now it is not going to build, since vala has updated to 0.46)  
https://github.com/philippejer/vala-language-server-alpha/issues/30

**Comment by Prince781** [comment]
@gavr123456789 it's something I'm looking into.

**Comment by gavr123456789** [comment]
@Prince781 Great to hear, I'll be waiting. Because when I updated to Vala 0.48, I found myself in an amazing situation with LS.   
This one is leaking, and to get all the functions I need to manually build Vala with MR(I'll definitely try it, the live documentation looks awesome, but I'm not particularly good at git)((and without MR, auto-complition only work for the root namespace))  
Philip's VLS is no longer compiling.  
Espinosa's GVLS as far as I understand is waiting for fixes from the Builder sid to start analyzing meson dependencies.(not sure about that)  
The larma plugin, on the contrary, complements only what is after the dot, and does not work for root namespace. (think now i will use it until leak fix comes out)

**Comment by Prince781** [comment]
It looks like `Vls.ListSymbol` is sticking around after going out of scope.

**Comment by Prince781** [comment]
@gavr123456789 the latest commit doesn't fix the issue of `Vls.ListSymbol` sticking around, but it prevents them from keeping the `Vala.CodeContext`s around. So memory consumption should go way down now.

**Comment by gavr123456789** [comment]
Just for the record: VLS is currently running at 2 megabytes per autocomplete.

**Comment by Prince781** [comment]
@gavr123456789 I've tested it and I don't seem to notice any memory leaks. Can you try it now and let me know? 

Note: one possible side-effect of this fix is that completion may be a bit slower now that we're properly destroying everything. That should be addressed in a separate issue.
