### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by mickeyl** [benwaffle/vala-language-server#6]
At last, I managed to compile and install the extension on macOS. While it seems to run ok (`ps -ef`), I can't really find it to make a difference, i.e., I don't think it actually autocompletes what I would be expecting. For a start… I try to reference a symbol from `linux.vapi` typing `Lin`, but it doesn't offer any completions. Ok, perhaps it didn't scan the vapis... trying to type `var x = Linux.InotifyE`, but it doesn't offer to complete it either.

Am I expecting anything it's not suggested to offer or does it not work here as expected? Is there a way to debug it?

**Comment by benwaffle** [comment]
Autocompletion is still a work in progress. We have some branches

**Comment by Prince781** [comment]
^ What Ben said.

If you're really interested, see the wip-completion2 branch.

**Comment by Prince781** [comment]
> I can't really find it to make a difference
While we're working on autocompletion, you should at least be getting syntax + semantic messages from the compiler. If you're not getting these, one possibility is that you're not using VLS in a Meson project and/or you have no `compile_commands.json` file. We introspect the `meson.build` in the workspace directory to figure out what source files are compiled and what their targets are, and introspect the `compile_commands.json` that Meson generates to figure out compiler commands and packages. You can also generate `compile_commands.json` for non-Meson projects by calling `bear make` instead of `make` (see https://github.com/rizsotto/Bear or check your package manager).

If you have none of these files, we have no way of determining what source files are compiled. We fallback to recursive search of all *.{vapi,vala} in your workspace while adding any newly-opened files to the source list. 

But you should be seeing some responses from VLS. If you're not, let us know.

**Comment by Prince781** [comment]
Since this "bug" doesn't address issues with unintentional behavior, and since we are working on completion, I am closing this.
