### ISSUE TITLE
Object members autocomplete doesn't work in certain contexts

### ISSUE THREAD

**Issue by ChronosX88** [benwaffle/vala-language-server#71]
**Description**: When I try to get completion list of some symbol, after typing ., server doesn't respond with list of member methods/properties available to call/get.  
**Vala version**: 0.48  
**Version of this language server**: 0.0.2 (got it from AUR package)  
**Logs**:
```
vls: main.vala:716: Request (78): context updated
vls: main.vala:1742: [textDocument/completion] FindSymbol @ 25:11
vls: main.vala:1749: [textDocument/completion] no results found for member access
```

**Comment by Prince781** [comment]
what client is this on?

**Comment by Prince781** [comment]
Okay, I see the nature of your problem now. Our approach has been to modify the Vala parser to accommodate autocomplete functionality, rather than doing all of the work in the language server. Bear in mind that there are currently limitations with the Vala 0.48 parser that will prevent you from seeing member access completion in many contexts. For example, you won't see member access completion in a situation like this:
```vala
void main() {
    thing. // <----
}
```

But you will see it in:
```vala
class Thing() {
    Thing() {
        this. // < ---
        this.x = 3;
    }
}
```
Because the parser currently can't handle incomplete member accesses before the end of a block. I'm currently working on a pull request for Vala master to address [this](https://gitlab.gnome.org/GNOME/vala/-/merge_requests/95). This might make it into a point release for Vala 0.48 or at the latest Vala 0.50. If the latter, then I might look into coming up with a quick fix in VLS.

**Comment by ChronosX88** [comment]
@Prince781 My client is VSCode

**Comment by Prince781** [comment]
@ChronosX88 I've just merged a lot of improvements to completion that address this issue. Please try out VLS from the latest commit and file a new issue for more completion problems you encounter.

**Comment by gavr123456789** [comment]
![Peek 2020-04-19 05-36](https://user-images.githubusercontent.com/30507409/79678042-d6e1fe80-81ff-11ea-8c23-17c6f4b0aed8.gif)
Looks like there still some bugs.

**Comment by Prince781** [comment]
@gavr123456789 that bug appears to be happening because `stdout` is part of `Posix`, and it's not imported. We should expect to see it implicitly imported, though.

Hmm...

**Comment by Prince781** [comment]
@gavr123456789 actually, forget my last comment. This is indeed strange.

**Comment by Prince781** [comment]
@gavr123456789 this commit (https://github.com/benwaffle/vala-language-server/commit/f2ab4b4912ad91bc6939db46c0182c80103d196c) should fix that issue
