### ISSUE TITLE
Support for C introspection from Vala code

### ISSUE THREAD

**Issue by EbonJaeger** [benwaffle/vala-language-server#86]
**Describe the feature(?)**
Not sure if this should be considered a feature or a bug, or even if it applies here, but I use this with a project that is mostly Vala but contains some C code that the Vala code links to. Currently, the language server doesn't take the C stuff into account, producing a lot of error popups in the editor because everything is assumed to be Vala.

Is there a way to make this work? Heck, is this even in scope for this project?

**Software**
OS and version (e.g. Ubuntu 20.04): Solus 4.1
Code editor (e.g. VSCode): VS Code
Vala Language Server (e.g. git commit, or PPA/AUR version): commit 2272f4f10c24dba5bffb42034ba813f9e2edf65f
Vala version (`valac --version`): 0.48.2

**Comment by Prince781** [comment]
This should be possible given the recent project backend rewrite. VLS now runs some of the build tasks in the Meson project if they happen to generate files needed by some Vala target. I've avoided handling targets that compile C code because it was something I hadn't had the time to test at the moment. If you can give me a project where this applies, I'll have a good example to work with when testing this feature.

**Comment by EbonJaeger** [comment]
Budgie Desktop. Shouldn't be hard to build; here are the things needed: https://github.com/solus-project/budgie-desktop/wiki/Building-Budgie-Desktop. One place in particular to look is in `src/panel/panel.vala`. Also, probably any of the applets.

**Comment by Prince781** [comment]
@EbonJaeger well, it involved a few hacks, but I managed to get this to work. Try out the `issue/support-c-introspection` branch and let me know what you think.

**Comment by EbonJaeger** [comment]
Seems to work fine to me so far. No more errors anywhere from the C code. Thanks!
